### ISSUE TITLE
Circular dependency with astropy?

### ISSUE THREAD

**Issue by pllim** [astropy/asdf-astropy#203]
I see this in https://github.com/astropy/astropy/pull/14784 (https://github.com/astropy/astropy/actions/runs/6114052860/job/16594815510?pr=14784)

```
Collecting astropy>=5.0.4 (from asdf-astropy==0.4.1.dev54+gcb80bd8)
  Downloading astropy-5.3.3.tar.gz (7.8 MB)
```

This makes no sense because CI in astropy should not result in any "Downloading astropy-5.3.3.tar.gz". I wonder if asdf-astropy should stop declaring astropy as required dependency...

https://github.com/astropy/asdf-astropy/blob/cb80bd82d7ad8d09d26c5b4ebb2d76cae3c71b0f/pyproject.toml#L23

**Comment by WilliamJamieson** [comment]
`astropy` is a required dependency of `asdf-astropy`. So we definitely have to declare it.

**Comment by pllim** [comment]
How do we prevent a dev install of asdf-astropy over at astropy CI trying to pull in an older astropy?

**Comment by pllim** [comment]
I don't think we should close this issue yet because this is preventing astropy from pulling in asdf-astropy for Python 3.12 testing.

**Comment by WilliamJamieson** [comment]
This is an `astropy` issue not an `asdf-astropy` issue. The problem you are referencing is simply due to how `astropy`'s `tox` configuration handles installing the dev dependencies. It simply needs to install `asdf-astropy` dev after `astropy` is installed.

**Comment by pllim** [comment]
OK. After discussions "offline", we agreed to remove installing dev version of asdf-astropy in astropy CI. This package is technically downstream now, so please be diligent in testing against astropy dev here instead. Thanks!
