### ISSUE TITLE
Copy semantics change in numpy 2.0 caused incompatibility with astropy v6.1rc

### ISSUE THREAD

**Issue by pllim** [astropy/asdf-astropy#226]
Please see:

* https://github.com/astropy/astropy/issues/16167
* https://github.com/astropy/astropy-integration-testing/pull/16
* https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword

```
E       ValueError: Unable to avoid copy while creating an array as requested.
E       If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
E       For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
```

Example logs:

https://github.com/astropy/astropy-integration-testing/actions/runs/8568043943/job/23485755895?pr=16

```
asdf==3.1.0
asdf-astropy==0.6.0
asdf_coordinates_schemas==0.3.0
asdf_standard==1.1.1
asdf_transform_schemas==0.5.0
asdf_unit_schemas==0.2.0
```

https://github.com/astropy/astropy-integration-testing/actions/runs/8568043943/job/23485756300?pr=16

```
asdf==3.1.0
asdf-astropy @ git+https://github.com/astropy/asdf-astropy.git@f7a29bab1b1ddfbebe3aea9b60acff7fbd2ee956
asdf_coordinates_schemas==0.3.0
asdf_standard==1.1.1
asdf_transform_schemas==0.5.0
asdf_unit_schemas==0.2.0
```

cc @astrofrog @neutrinoceros

**Comment by braingram** [comment]
This was already addressed in:
https://github.com/astropy/asdf-astropy/pull/224

A release will be out soon (once jwst testing passes):
https://github.com/astropy/asdf-astropy/pull/225
