### ISSUE TITLE
Review of what else should go in this package

### ISSUE THREAD

**Issue by nden** [astropy/asdf-astropy#3]
What other tags should be moved from astropy here?

astropy.io.asdf.tags:
  coordinates                           
  fits
  table
  time
  unit/equivalency

**Comment by jdavies-st** [comment]
I think it is good to move all the tags out of `astropy` into this package.

At a later date, really anytime, if we want to move the schemas into a more general schema repositories on `asdf-standard`, say for `coordinates`, then it would be simple to do so and have `asdf-astropy` manage the interface for it.  It should be transparent to `astropy`.  Any modifications to the `Converter` classes or schema tags can be handled here.

Specifically:

- `coordinates` schema is very general and might benefit from schemas being in `asdf-format/asdf-coordinate-schemas` or similar
- `fits` schema should stay in this package.
- `table` schema seems to be specific to `astropy.tables`.  There's also a `table` and `column` schema in `asdf-format/asdf-standard` core libarary, that has some underpinnings with FITS binary tables, but it's not clear to me that one is more general than another.  I would say keep it here.
- `time` schemas already live in `asdf-format/asdf-standard` except for `time-delta`.  Shall we move it there or is it more astronomy-specific.  How stable is it?
- `unit` schemas live in `asdf-standard` already.  Do we move `equivalency` here?  Or should it be moved to `asdf-standard`?

**Comment by jdavies-st** [comment]
I'll add that #5 already moves copies the schemas from `astropy.io.misc.asdf` into this repo.

https://github.com/astropy/asdf-astropy/tree/ba36c0ac09a7d9fadaff6dcee8f2fb968d076bd0/asdf_astropy/resources/schemas

👍

**Comment by eslavich** [comment]
These have all been moved into this package! 🥳
