### ISSUE TITLE
DOC: Getting started should have a quick-start example

### ISSUE THREAD

**Issue by pllim** [astropy/asdf-astropy#72]
"Getting Started" looks pretty sparse:

![Screenshot 2022-05-19 151149](https://user-images.githubusercontent.com/2090236/169384360-fa912d3e-5e45-42e5-b0d4-f17bb7483b95.png)

What happens after installation? Would be nice to actually have "getting started to use the package" example too, not just installation.

**Comment by WilliamJamieson** [comment]
There is no "quick-start" example here, `asdf-astropy` is just an extension library for `asdf` which provides the necessary features to serialize supported `astropy` objects. Any quick-start is equivalent to getting started with `asdf` (only with writing `astropy` specific objects). Would a link to `asdf`'s [hello world](https://asdf.readthedocs.io/en/latest/asdf/overview.html#hello-world) be sufficient.

**Comment by pllim** [comment]
Hmm, perhaps that is sufficient or feel free to close if you think this request is not actionable.
