### ISSUE TITLE
Not all `astropy.time` formats appear to be supported correctly.'

### ISSUE THREAD

**Issue by WilliamJamieson** [astropy/asdf-astropy#85]
In looking at the coverage reports for `asdf-astropy` I noticed that the `astropy.time` time-formats covered by: https://github.com/astropy/asdf-astropy/blob/816dc57584a3735286e9d73f7d622570ecfc0507/asdf_astropy/converters/time/time.py#L22-L27 are not being properly tested by the `asdf-astropy` unit tests. However, when I added test-cases to cover these formats, I discovered that times using these formats do not round-trip through asdf using `asdf-astropy`. Note that this extends to when one uses `astropy.io.misc.asdf` as well.

We claim that `asdf-astropy` will produce an identical `astropy` object to that which was serialized for all supported `astropy` objects. This is clearly not happening at this time.

**Comment by WilliamJamieson** [comment]
Tagging @mhvk and @taldcroft, for their advice on refactoring the time converter: https://github.com/astropy/asdf-astropy/blob/816dc57584a3735286e9d73f7d622570ecfc0507/asdf_astropy/converters/time/time.py#L14-L104 in general. Any advice on improving/simplifying this object would be great.

**Comment by mhvk** [comment]
@WilliamJamieson - in newer astropy, the way to ensure precision is not lost when using a string representation is
```
from astropy.time import Time
t = Time(50000., 1/9, format='mjd')
t.to_value('mjd', 'str')
# '50000.1111111111111111'
```
Note that this will round-trip for MJD, but not for BYEAR, since the latter involves a calculation that uses a single `float`. But at least it should be considerably closer.

**Comment by WilliamJamieson** [comment]
@mhvk, in an offline conversation with @taldcroft, it was suggested that maybe we should use something like `Time.info._represent_as_dict()`, which should be "stable". This would let us serialize the JD1/JD2 representation that astropy is using to represent the given time, which should round trip?

If this seems like an option, we might require something like a `to_dict` (or `to_yaml`) and `from_dict` method to be added to `astropy.time.Time` which we could then use a new `Converter` and `schema` for.

**Comment by mhvk** [comment]
@WilliamJamieson - I think explicitly using the methods astropy uses internally to serialize objects makes sense. I'm not quite sure that this would need a method on `Time` itself, especially since you may well want a similar procedure for `SkyCoord`. Perhaps instead we should just make our current machinery public? (Could be functions or public methods on `.info`.)

**Comment by WilliamJamieson** [comment]
> Could be functions or public methods on `.info`.

This is fine, I just would prefer to use some sort of public interface to both serialize and deserialize (construct) `Time` objects using the representations astropy works with internally. That way I can rely on the interface being consistent.
